# Generated by Django 4.2.6 on 2023-12-09 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('proposedUser', models.CharField(blank=True, max_length=225, null=True)),
                ('key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id', models.URLField(null=True)),
                ('host', models.URLField(default='https://cmput404-social-network-401e4cab2cc0.herokuapp.com/', null=True)),
                ('displayName', models.CharField(max_length=32)),
                ('url', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('profileImage', models.URLField(null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('contentType', models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain Text'), ('application/base64', 'Base64-encoded'), ('image/png;base64', 'Embedded PNG'), ('image/jpeg;base64', 'Embedded JPEG')], default='text/plain', max_length=255)),
                ('comment', models.TextField(max_length=255)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.URLField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.author')),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='Follow', editable=False, max_length=50)),
                ('summary', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='social_media.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='social_media.author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('contentType', models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain Text'), ('application/base64', 'Base64-encoded'), ('image/png;base64', 'Embedded PNG'), ('image/jpeg;base64', 'Embedded JPEG')], default='text/plain', max_length=255)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends')], default='PUBLIC', max_length=10)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.URLField(null=True)),
                ('origin', models.URLField(editable=False)),
                ('description', models.TextField(default='Wow what a description', editable=False)),
                ('categories', models.JSONField(null=True)),
                ('count', models.IntegerField(default=0)),
                ('comments', models.URLField(editable=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('unlisted', models.BooleanField()),
                ('commentsSrc', models.JSONField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.author')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('remote_ip', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.URLField(editable=False)),
                ('object', models.URLField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.author')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.post')),
            ],
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=225)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.author')),
                ('follow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.followrequest')),
                ('like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.like')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.post')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='social_media.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='social_media.author')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.post'),
        ),
    ]
